Another test

diff --git a/0x02-shell_redirections/testing b/0x02-shell_redirections/testing
--- a/0x02-shell_redirections/testing
+++ b/0x02-shell_redirections/testing
@@ -1,2 +1,8 @@
 #!/bin/bash
-echo "$1 baby"
+if [$1 -eq 0];
+then
+	echo "Message Missing"
+	exit 1
+else
+	echo "$1"
+fi
